# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::r-quilt=2.0.2=r44h503566f_0
  - r-base=4.4.3
  - r-r.utils
