# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: cuteSV2_SVUPP
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - git+https://github.com/Zilong-Li/cuteSV.git@v0.0.2
    

