name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v2
      - run: nextflow run ${GITHUB_WORKSPACE} -h

      - name: install samtools
        run: |
          sudo apt-get update -y
          sudo apt-get install -qy build-essential samtools

      - name: Download data
        run: sudo bash ./scripts/download-examples.sh

      - name: Test examples
        run: |
          nextflow run main.nf \
          -profile conda \
          --refpanel tests/refpanel.csv \
          --samples tests/samples.csv \
          --svfile tests/delins.sniffles.hg38.liftedT2T.13Nov2023.nygc.vcf.gz

